server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
            locator:
              enabled: true
      routes:
        #路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #lb代表从注册中心获取服务,后接需要的服务名称
          uri: lb://CLOUD-PAYMENT-SERVICE
          #断言,路径相匹配的进行路由
          predicates:
            - Path=/payment/get/**
            - After=2020-09-27T18:04:01.989+08:00[Asia/Shanghai]
            - Cookie=chocolate,choco
            - Header=req, \d+

        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
    prefer-ip-address: true
    instance-id: cloud-gateway-service
  client:
    service-url:
      regitster-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
