server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        #路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
          #匹配后提供服务的路由地址
          uri: http://localhost:8001
          #断言,路径相匹配的进行路由
          predicates:
            - Path=/payment/get/**

        #路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh2
          #匹配后提供服务的路由地址
          uri: http://localhost:8001
          #断言,路径相匹配的进行路由
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
    prefer-ip-address: true
    instance-id: cloud-gateway-service
  client:
    service-url:
      regitster-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
